(executable
 (name proof_mode_tool)
 (libraries verocaml_core compiler-libs.common))
(cram
 (deps (glob_files fixtures/*.ml) proof_mode_tool.exe ../../verocaml.install
  ../../ppx/vero_ppx.exe ../../runtime/vero_ghost.cma
  ../../runtime/.vero_ghost.objs/byte/vero_ghost.cmi))
(alias (name proof-mode-check) (deps (alias runtest)))
