(library
 (name vstd_consumer)
 (modules vstd_consumer)
 (libraries verocaml.vstd verocaml.ghost)
 (flags (:standard -w -A -alert -all))
 (preprocess (pps vero_ppx_driver)))

(library
 (name ambient_vstd_consumer)
 (modules ambient_vstd_consumer)
 (libraries verocaml.vstd verocaml.ghost)
 (flags (:standard -w -A -alert -all))
 (preprocess (pps vero_ppx_driver)))

(library
 (name imported_generic_axiom_consumer)
 (modules imported_generic_axiom_consumer)
 (libraries verocaml.vstd verocaml.ghost)
 (flags (:standard -w -A -alert -all -open Vstd))
 (preprocess (pps vero_ppx_driver)))

(cram
 (deps
  ../../src/verocaml.exe
  .vstd_consumer.objs/byte/vstd_consumer.cmt
  .ambient_vstd_consumer.objs/byte/ambient_vstd_consumer.cmt
  .imported_generic_axiom_consumer.objs/byte/imported_generic_axiom_consumer.cmt
  (alias ../../library/all)))
