(executable
 (name release_verification_tool)
 (libraries verocaml_core))

(cram
 (deps
  (glob_files fixtures/*.ml)
  (glob_files fixtures/*.mli)
  release_verification_tool.exe
  ../../src/verocaml.exe
  ../../ppx/vero_ppx.exe
  ../../runtime/vero_ghost.cma
  ../../runtime/.vero_ghost.objs/byte/vero_ghost.cmi))

(alias
 (name release-verification-check)
 (deps
  (alias runtest)))
