(library
 (name vero_ppx_rewriter)
 (public_name verocaml.ppx-rewriter)
 (modules
  vero_ppx_logical_builtin_private
  vero_ppx_broadcast_private
  vero_ppx_symbolic_private
  vero_ppx_rewriter)
 (private_modules
  vero_ppx_logical_builtin_private
  vero_ppx_broadcast_private
  vero_ppx_symbolic_private)
 (libraries compiler-libs.common delator)
 (preprocess
  (pps delator.ppx -- --static-level=%{env:DELATOR_STATIC_LEVEL=info})))

(library
 (name vero_ppx_driver)
 (public_name verocaml.ppx)
 (kind ppx_rewriter)
 (modules vero_ppx_driver)
 (libraries vero_ppx_rewriter ppxlib delator)
 (preprocess
  (pps delator.ppx -- --static-level=%{env:DELATOR_STATIC_LEVEL=info})))

(executable
 (name vero_ppx)
 (public_name verocaml-ppx)
 (package verocaml)
 (modules vero_ppx)
 (libraries vero_ppx_rewriter compiler-libs.common delator)
 (preprocess
  (pps delator.ppx -- --static-level=%{env:DELATOR_STATIC_LEVEL=info})))
